name: DevSecOps pipeline 
on:
  push:
    branches: [ main, devsecops ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'screenshots/**'
      - 'scripts/**'

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
